blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/twinbolt/giraff/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Get help from the Home Assistant community
