name: "Stuga Dashboard"
description: "A mobile-first, Scandinavian-minimal Home Assistant dashboard"
version: "1.1.1"
slug: "stuga"
url: "https://github.com/twinbolt-ab/stuga"
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 3001
panel_icon: "mdi:view-dashboard"
panel_title: "Stuga"
panel_admin: false
startup: "application"
init: false
ports:
  3001/tcp: 3001
host_network: true
